# Generated by Django 6.0.1 on 2026-03-23 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailnotificationlog',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Notification Log', 'verbose_name_plural': 'Notification Logs'},
        ),
        migrations.AddField(
            model_name='emailnotificationlog',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailnotificationlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
