# Generated by Django 6.0.1 on 2026-03-22 11:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('debit_physical', 'Physical Debit Card'), ('debit_virtual', 'Virtual Debit Card'), ('prepaid', 'Prepaid Card')], default='debit_virtual', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('lost_stolen', 'Reported Lost/Stolen')], default='active', max_length=20)),
                ('card_number', models.CharField(editable=False, max_length=19, unique=True)),
                ('expiry_date', models.DateField()),
                ('cvv', models.CharField(editable=False, max_length=3)),
                ('daily_spend_limit', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=12)),
                ('transaction_limit', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=12)),
                ('used_today', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='accounts.account')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='CardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('merchant_name', models.CharField(blank=True, max_length=255)),
                ('merchant_category', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='approved', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cards.card')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['account', 'status'], name='cards_card_account_9f6965_idx'),
        ),
    ]
