# Generated by Django 6.0.1 on 2026-03-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_pin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardtransaction',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Card Transaction', 'verbose_name_plural': 'Card Transactions'},
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('declined', 'Declined'), ('pending', 'Pending')], default='approved', max_length=20),
        ),
    ]
