# Generated by Django 6.0.1 on 2026-03-22 11:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_debited', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transfer_type', models.CharField(choices=[('internal_same_user', 'Between own accounts'), ('internal_other_user', 'To another Spartan user'), ('external_mpesa', 'To M-Pesa'), ('external_pesalink', 'To other bank via Pesalink'), ('bill_payment', 'Bill / Airtime payment')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=100)),
                ('external_provider', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('receiver_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to='accounts.account')),
                ('sender_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transfers', to='accounts.account')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100)),
                ('result_code', models.IntegerField(null=True)),
                ('result_description', models.TextField(blank=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('callback_received_at', models.DateTimeField(blank=True, null=True)),
                ('transfer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_tx', to='payments.transfer')),
            ],
            options={
                'verbose_name_plural': 'M-Pesa Transactions',
            },
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['sender_account', 'status'], name='payments_tr_sender__68aceb_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['external_reference'], name='payments_tr_externa_521476_idx'),
        ),
    ]
