# Generated by Django 6.0.1 on 2026-03-23 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transfer',
            name='payments_tr_sender__68aceb_idx',
        ),
        migrations.RemoveIndex(
            model_name='transfer',
            name='payments_tr_externa_521476_idx',
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='checkout_request_id',
            field=models.CharField(blank=True, help_text='Daraja CheckoutRequestID', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='transfer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transaction', to='payments.transfer'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='external_provider',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='receiver_account',
            field=models.ForeignKey(blank=True, help_text='Destination account (null for external/M-Pesa withdrawals)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sender_account',
            field=models.ForeignKey(help_text='The account from which money is leaving (or target account for deposits)', on_delete=django.db.models.deletion.PROTECT, related_name='sent_transfers', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending (Admin Review)'), ('mpesa_confirmed', 'M-Pesa Confirmed'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(choices=[('internal_same_user', 'Between own accounts'), ('internal_other_user', 'To another Spartan user'), ('external_mpesa', 'To M-Pesa'), ('deposit_mpesa', 'M-Pesa Deposit'), ('withdraw_mpesa', 'M-Pesa Withdrawal'), ('external_pesalink', 'To other bank via Pesalink'), ('bill_payment', 'Bill / Airtime payment')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['checkout_request_id'], name='payments_mp_checkou_a6f836_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['transfer'], name='payments_mp_transfe_193a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['reference'], name='payments_tr_referen_d637ab_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['status', 'transfer_type'], name='payments_tr_status_0d5539_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['sender_account', 'initiated_at'], name='payments_tr_sender__d9f3c1_idx'),
        ),
    ]
