# Generated by Django 6.0.1 on 2026-03-24 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0002_remove_transfer_payments_tr_sender__68aceb_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mpesatransaction',
            name='payments_mp_checkou_a6f836_idx',
        ),
        migrations.RemoveIndex(
            model_name='mpesatransaction',
            name='payments_mp_transfe_193a7a_idx',
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='external_provider',
            field=models.CharField(blank=True, default='mpesa_till', max_length=50),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='external_reference',
            field=models.CharField(blank=True, help_text='M-Pesa Receipt Number (e.g. LHG123456K)', max_length=100),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='receiver_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sender_account',
            field=models.ForeignKey(help_text='Target account for deposits', on_delete=django.db.models.deletion.PROTECT, related_name='sent_transfers', to='accounts.account'),
        ),
    ]
