# Generated by Django 6.0.1 on 2026-03-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_mpesatransaction_payments_mp_checkou_a6f836_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(choices=[('internal_same_user', 'Between own accounts'), ('internal_other_user', 'To another Spartan user'), ('external_mpesa', 'To M-Pesa'), ('deposit_mpesa', 'M-Pesa Deposit'), ('withdraw_mpesa', 'M-Pesa Withdrawal'), ('external_pesalink', 'To other bank via Pesalink'), ('bill_payment', 'Bill / Airtime payment'), ('loan_disbursement', 'Loan Disbursement')], max_length=30),
        ),
    ]
