# Generated by Django 6.0.1 on 2026-03-22 11:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('checking', 'Checking'), ('loan', 'Loan Account')], default='savings', max_length=10)),
                ('account_number_encrypted', models.BinaryField(blank=True, null=True)),
                ('balance_encrypted', models.BinaryField(blank=True, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=3.5, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('term_months', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('repaid', 'Fully Repaid')], default='pending', max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='accounts.account')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdrawal'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('interest', 'Interest'), ('fee', 'Fee'), ('loan_disbursement', 'Loan Disbursement'), ('loan_repayment', 'Loan Repayment')], max_length=20)),
                ('category', models.CharField(blank=True, choices=[('salary', 'Salary / Income'), ('business', 'Business / Sales'), ('remittance', 'Remittance / Money Received'), ('groceries', 'Groceries / Food'), ('transport', 'Transport / Fuel'), ('utilities', 'Utilities / Bills'), ('education', 'Education / School Fees'), ('health', 'Medical / Health'), ('entertainment', 'Entertainment / Leisure'), ('shopping', 'Shopping / Personal'), ('travel', 'Travel'), ('investment', 'Investment / Savings'), ('loan', 'Loan Related'), ('other', 'Other')], default='', help_text='User-selected category for budgeting and reporting', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.account')),
                ('related_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to='accounts.account')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, unique=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('national_id', models.CharField(blank=True, max_length=50)),
                ('kyc_verified', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True)),
                ('security_question', models.CharField(blank=True, max_length=255)),
                ('security_answer_hash', models.CharField(blank=True, max_length=255)),
                ('mfa_enabled', models.BooleanField(default=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('daily_deposit_limit', models.DecimalField(decimal_places=2, default=Decimal('500000.00'), help_text='Max total deposits per day (KES)', max_digits=12)),
                ('daily_withdrawal_limit', models.DecimalField(decimal_places=2, default=Decimal('500000.00'), help_text='Max total withdrawals per day (KES)', max_digits=12)),
                ('daily_transfer_limit', models.DecimalField(decimal_places=2, default=Decimal('500000.00'), help_text='Max total outgoing transfers per day (KES)', max_digits=12)),
                ('daily_outflow_limit', models.DecimalField(decimal_places=2, default=Decimal('1000000.00'), help_text='Combined daily limit for withdrawals + outgoing transfers (KES)', max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', 'created_at'], name='accounts_ac_user_id_452791_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trusteddevice',
            unique_together={('user', 'token')},
        ),
    ]
