# Generated by Django 6.0.1 on 2026-03-24 21:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanapplication',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='amount_disbursed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='disbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='last_repayment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_loan_application', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='total_interest',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='total_repaid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('repaid', 'Fully Repaid'), ('defaulted', 'Defaulted')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('salary', 'Salary / Income'), ('business', 'Business / Sales'), ('remittance', 'Remittance / Money Received'), ('groceries', 'Groceries / Food'), ('transport', 'Transport / Fuel'), ('utilities', 'Utilities / Bills'), ('education', 'Education / School Fees'), ('health', 'Medical / Health'), ('entertainment', 'Entertainment / Leisure'), ('shopping', 'Shopping / Personal'), ('travel', 'Travel'), ('investment', 'Investment / Savings'), ('loan', 'Loan Related'), ('other', 'Other')], default='', max_length=50),
        ),
        migrations.CreateModel(
            name='LoanSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('principal_component', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_component', models.DecimalField(decimal_places=2, max_digits=14)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid', models.BooleanField(default=False)),
                ('actual_payment_date', models.DateTimeField(blank=True, null=True)),
                ('late_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='accounts.loanapplication')),
            ],
            options={
                'ordering': ['due_date'],
                'unique_together': {('loan', 'due_date')},
            },
        ),
    ]
