# Generated by Django 6.0.1 on 2026-03-28 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_loanapplication_options_and_more'),
        ('payments', '0004_alter_transfer_transfer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='disbursement_transfer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_loan', to='payments.transfer'),
        ),
    ]
