# Generated by Django 6.0.1 on 2026-03-28 11:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_loanapplication_disbursement_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='daily_deposit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('500000.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_outflow_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000000.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_transfer_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('500000.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_withdrawal_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('500000.00'), max_digits=12),
        ),
    ]
