# Generated by Django 6.0.1 on 2026-03-28 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_daily_deposit_limit_and_more'),
        ('payments', '0004_alter_transfer_transfer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='disbursement_transfer',
            field=models.OneToOneField(blank=True, help_text='The pending/completed transfer that disbursed this loan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_disbursement', to='payments.transfer'),
        ),
    ]
