# Generated by Django 6.0.1 on 2026-03-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_loanapplication_disbursement_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trusteddevice',
            name='biometric_type',
            field=models.CharField(choices=[('fingerprint', 'Fingerprint'), ('face_id', 'Face ID'), ('other', 'Other Biometric')], default='fingerprint', max_length=20),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='is_biometric',
            field=models.BooleanField(default=False, help_text='This device was registered using fingerprint/face ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='biometric_enabled',
            field=models.BooleanField(default=False, help_text='User has enabled fingerprint or face ID login'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_biometric_login',
            field=models.DateTimeField(blank=True, help_text='Last successful biometric login timestamp', null=True),
        ),
    ]
