# Generated by Django 6.0.1 on 2026-03-22 11:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirtimeProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('short_name', models.CharField(max_length=20)),
                ('default_paybill', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('paybill_number', models.CharField(blank=True, max_length=20)),
                ('account_number_label', models.CharField(blank=True, max_length=80)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, default=Decimal('500000.00'), max_digits=12)),
                ('icon_class', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Bill Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paybill_number', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_debited', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('external_reference', models.CharField(blank=True, max_length=100)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('transfer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_payment', to='payments.transfer')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_payments', to='accounts.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bills.billcategory')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='DataBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_amount', models.CharField(max_length=50)),
                ('validity_days', models.PositiveIntegerField(default=1)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='bills.airtimeprovider')),
            ],
            options={
                'ordering': ['provider', 'amount'],
            },
        ),
        migrations.CreateModel(
            name='AirtimeTopup',
            fields=[
                ('billpayment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bills.billpayment')),
                ('phone_number', models.CharField(max_length=15)),
                ('is_bundle', models.BooleanField(default=False)),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bills.databundle')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bills.airtimeprovider')),
            ],
            options={
                'verbose_name': 'Airtime / Bundle Top-up',
            },
            bases=('bills.billpayment',),
        ),
        migrations.AddIndex(
            model_name='billpayment',
            index=models.Index(fields=['user_account', 'status'], name='bills_billp_user_ac_ccc436_idx'),
        ),
        migrations.AddIndex(
            model_name='billpayment',
            index=models.Index(fields=['reference'], name='bills_billp_referen_1b042a_idx'),
        ),
        migrations.AddIndex(
            model_name='billpayment',
            index=models.Index(fields=['external_reference'], name='bills_billp_externa_f5e65c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='databundle',
            unique_together={('provider', 'amount', 'data_amount')},
        ),
    ]
